export enum RouterPaths {
    LANDING = "/",
    LOGIN = "/login",
    REGISTER = "/register",
    RIDE = "/ride",
    COMPLAIN = "/complain",
    HOMEDELIVERY = "/delivery",
    ORDER = "/order/:id",
    SEARCHDELIVERY = "/delivery/search",
    SEARCHRIDE = "/ride/search",
    PROFILE = "/profile",
    CREATERIDE = "/ride/create",
    CONTACT = "/contact",
    DRIVERREGISTER = "/drive/register",
    ORDERDELIVERY = "/delivery/order",
    DRIVERDASHBOARD = "/dashboard",
    DASHBOARDRIDES = "/dashboard/rides",
    DASHBOARDREQUESTS = "/dashboard/requests",
    DASHBOARDHOME = "/dashboard/home",
}

