export enum RouterPaths {
    LANDING = "/",
    LOGIN = "/login",
    REGISTER = "/register",
    RIDE = "/ride",
    COMPLAIN = "/complain",
    HOMEDELIVERY = "/delivery",
    ORDER = "/order/:id",
    SEARCHDELIVERY = "/delivery/search",
    SEARCHRIDE = "/ride/search",
    PROFILE = "/profile",
    CREATERIDE = "/ride/create",
    CONTACT = "/contact",
    DRIVERREGISTER = "/drive/register",
    DRIVERDASHBOARD = "/dashboard",
    DASHBOARDRIDES = "/dashboard/rides",
    DASHBOARDREQUESTS = "/dashboard/requests",
    DASHBOARDHOME = "/dashboard/home",
    MYRIDES = "/myrides",
    ORDERDELIVERY = "/delivery/order/:id",
    ADMINDASHBOARD = "/admin-dashboard",
    ADMINHOME = "/admin-dashboard/home",
    ADMINUSERS = "/admin-dashboard/users",
    ADMINDISPUTE = "/admin-dashboard/dispute",
    ADMINDRIVERREGREQUEST = "/admin-dashboard/registration-request",
    ADMINANALYTICS = "/admin-dashboard/analytics"
}

